remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: [BlackBox_GGWP]
description: [Decentralization, future technology, digital freedom, human evolution, AI, blockchain, open-source, collective intelligence, resistance, anti-authoritarian, web3, decentralized governance, crypto, censorship resistance, innovation, science, digital sovereignty, post-collapse survival.]
